#!/usr/bin/env python3
"""Re-sync the vendored NIST SP 800-53 Rev 5 control catalog from its OSCAL JSON source.

The OSCAL catalog is U.S. government work in the public domain, so the full catalog can be vendored.
Run this on a networked host when NIST ships a new Rev 5 point release:

    python3 sync_nist80053.py

It fetches the OSCAL catalog, walks groups -> controls -> enhancements, builds a {display-id: title} map
(OSCAL `ac-2.1` is normalized to the display form `AC-2(1)`), reads the metadata version, regenerates the
catalog, and prints a review diff (added / removed / renamed) so a human can approve before committing.
Stdlib only (the source is JSON).

Note: the shipped catalog is a representative subset so the skill runs offline; this regenerates the full
Rev 5 set.
"""
from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

OSCAL_URL = (
    "https://raw.githubusercontent.com/usnistgov/oscal-content/main/"
    "nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json"
)
CATALOG = Path(__file__).parent / "nist-800-53-catalog.json"
OSCAL_ID_RE = re.compile(r"^[a-z]{2}-\d+(?:\.\d+)?$")


def fetch_oscal() -> bytes:
    req = urllib.request.Request(OSCAL_URL, headers={"User-Agent": "nist80053-sync"})
    with urllib.request.urlopen(req, timeout=60) as r:  # noqa: S310 (trusted NIST/GitHub host)
        return r.read()


def to_display_id(oscal_id: str) -> str:
    """OSCAL `ac-2` -> `AC-2`; `ac-2.1` -> `AC-2(1)` (enhancement in display form, no dot)."""
    base, _, enh = oscal_id.partition(".")
    fam, _, num = base.partition("-")
    disp = f"{fam.upper()}-{num}" if num else base.upper()
    return f"{disp}({enh})" if enh else disp


def collect_controls(node, out: dict[str, str]) -> None:
    """Recurse groups and controls (enhancements nest as a control's own `controls`)."""
    if isinstance(node, dict):
        cid, title = node.get("id"), node.get("title")
        if isinstance(cid, str) and OSCAL_ID_RE.match(cid) and isinstance(title, str):
            out[to_display_id(cid)] = " ".join(title.split())
        for key in ("groups", "controls"):
            for child in node.get(key, []) or []:
                collect_controls(child, out)
    elif isinstance(node, list):
        for child in node:
            collect_controls(child, out)


def main() -> int:
    doc = json.loads(fetch_oscal())
    catalog_root = doc.get("catalog", doc) if isinstance(doc, dict) else {}
    controls: dict[str, str] = {}
    for group in catalog_root.get("groups", []) or []:
        collect_controls(group, controls)
    version = str((catalog_root.get("metadata") or {}).get("version", ""))

    if not controls:
        print("ERROR: parsed 0 controls; aborting (catalog left unchanged).", file=sys.stderr)
        return 1

    old = json.loads(CATALOG.read_text()).get("catalog", {}) if CATALOG.exists() else {}
    added = sorted(set(controls) - set(old))
    removed = sorted(set(old) - set(controls))
    renamed = sorted(k for k in set(controls) & set(old) if controls[k] != old[k])

    print(f"controls: {len(controls)}   version: {version or '(none in metadata)'}")
    print(f"added:   {len(added)}")
    print(f"removed: {removed or 'none'}")
    print("renamed: " + (str([f"{k}: {old[k]!r} -> {controls[k]!r}" for k in renamed]) if renamed else "none"))

    out = {
        "version": version or "0.0.0+unknown",
        "source": OSCAL_URL,
        "note": "NIST SP 800-53 Rev 5 (OSCAL), U.S. government work in the public domain. Generated by "
                "sync_nist80053.py. Enhancement ids are stored in display form (AC-2(1)), not OSCAL dotted "
                "form (ac-2.1).",
        "catalog": {k: controls[k] for k in sorted(controls)},
    }
    with open(CATALOG, "w") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"wrote {CATALOG.name} (review the diff above, then commit).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
